### ISSUE TITLE
Goroutine for timer

### ISSUE THREAD

**Issue by milkaxq** [gophercises/quiz#126]
Hello. I wrote code that looks like [mycode](https://github.com/milkaxq/simple-cli-quiz/blob/main/main.go). So I wanted to ask about difference between creating 2 channels (answer and time) and 1 goroutine for timer only is there any disadvantages in my code?

**Comment by joncalhoun** [comment]
Unfortunately I don't have the capacity to do in-depth code reviews or to provide much 1-on-1 support for these exercises anymore, but glancing at your code I would say the primary difference is that in your code it would be much harder to start a second quiz immediately after the first one ends, especially if the first one ends with a timeout. If you want to see it first hand, attempt to update your code so that the user takes two different quizzes back to back before the program terminates. What happens if they timeout the first quiz and then you try to start the second quiz?
